spring:
  application:
    name: jenkins-demo
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'